//! Comptime manifest of the batch fixtures — ~1000 distinct cells of one
//! DGGS family at one resolution. Their purpose today is **timing**: they
//! are the survey workload at scale, the hot path CLAUDE.md describes,
//! for `csar-ab` to time per family and resolution. The one
//! contract, held by `tests/batches_test.zig` rather than stored per
//! file: every cell converges at `cases.pin` — a non-converging cell
//! would time `max_outer`, not the solver. A cell that stops converging
//! is a regression signal to investigate, not a count to bump (CLAUDE.md's
//! rule for the `h3_*` fixtures); every batch converges in full under
//! both backends — enforced by that contract test. Studying *which*
//! cells converge lives elsewhere: tests/frontier_test.zig pins
//! per-rung convergence counts on its own (untimed) synthetic cells.
//!
//! Generated by scripts/batches/gen_batches.py; the `.ids` beside each
//! `.zon` is the portable artifact. Plain `@import`, like the case
//! fixtures — measured cheap; dev.md "Test layout" has the numbers and
//! the data size at which a runtime loader becomes the right shape.

pub const Batch = struct {
    description: []const u8,
    cells: []const []const [3]f64,
};

pub const Entry = struct {
    name: []const u8,
    batch: Batch,
};

pub const all: []const Entry = &.{
    .{ .name = "h3_r9", .batch = @import("batches/h3_r9.zon") },
    .{ .name = "h3_r15", .batch = @import("batches/h3_r15.zon") },
    .{ .name = "s2_L15", .batch = @import("batches/s2_L15.zon") },
    .{ .name = "s2_L19", .batch = @import("batches/s2_L19.zon") },
    .{ .name = "s2_L23", .batch = @import("batches/s2_L23.zon") },
    .{ .name = "a5_r14", .batch = @import("batches/a5_r14.zon") },
    .{ .name = "a5_r18", .batch = @import("batches/a5_r18.zon") },
    .{ .name = "a5_r23", .batch = @import("batches/a5_r23.zon") },
};
