//! Comptime manifest of the batch fixtures — ~1000 distinct cells of one
//! DGGS family at one resolution. Their purpose today is **timing**: they
//! are the survey workload at scale, the hot path CLAUDE.md describes,
//! for `csar-ab` to time per family and resolution (#37). Every cell
//! converges, and the test below the manifest holds that line — a
//! non-converging cell burns `max_outer` and would time the cap, not the
//! solver. Studying *which* cells converge (per-family rates, the f64
//! floor) is deliberately later work with its own fixtures; these are
//! not that. Generated by scripts/batches/gen_batches.py; the `.ids`
//! beside each `.zon` is the portable artifact it was emitted from.
//!
//! Plain `@import`, like the case fixtures: ten 430 KB files measured at
//! +0.25 s on a cold `zig build test` and +130 MB compiler peak RSS (dev.md
//! "Test layout" has the numbers and the size at which a runtime loader
//! becomes the right shape instead).

/// The contract is the same for every batch and is not stored per file:
/// every cell converges at `cases.PIN` (`tests/batches_test.zig`), which
/// is what makes a batch's timing mean something. A cell that stops
/// converging is a regression signal to investigate, not a count to bump
/// — the same rule CLAUDE.md sets for the `h3_*` fixtures. Measured at
/// #36: all eight batches converge in full under both backends, so no
/// batch sits at the f64 gap floor.
pub const Batch = struct {
    description: []const u8,
    cells: []const []const [3]f64,
};

pub const Entry = struct {
    name: []const u8,
    batch: Batch,
};

pub const all: []const Entry = &.{
    .{ .name = "h3_r9", .batch = @import("batches/h3_r9.zon") },
    .{ .name = "h3_r15", .batch = @import("batches/h3_r15.zon") },
    .{ .name = "s2_L15", .batch = @import("batches/s2_L15.zon") },
    .{ .name = "s2_L19", .batch = @import("batches/s2_L19.zon") },
    .{ .name = "s2_L23", .batch = @import("batches/s2_L23.zon") },
    .{ .name = "a5_r14", .batch = @import("batches/a5_r14.zon") },
    .{ .name = "a5_r18", .batch = @import("batches/a5_r18.zon") },
    .{ .name = "a5_r23", .batch = @import("batches/a5_r23.zon") },
};
